app/urls.py
from django.urls import path
from app.views import (
    index as index_view,
    LessonListView,
    CompleteLessonView,
    CancelLessonView,
)
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", index_view, name="home"),
    path("lessons/", LessonListView.as_view(), name="lesson-list"),
    path(
        "lesson/<int:lesson_id>/cancel/",
        CancelLessonView.as_view(),
        name="cancel_lesson",
    ),
    path(
        "lesson/<int:lesson_id>/complete/",
        CompleteLessonView.as_view(),
        name="complete_lesson",
    ),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("app.urls")),
    path("", include("users.urls")),
    path("", include("tutors.urls")),
    path("", include("gglcalendar.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from users.views import (
    UserLoginView,
    UserLogoutView,
    student_signup,
    tutor_signup,
    PersonDetailUpdateView,
    PublicProfileView,
    activate,
)
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("login/", UserLoginView.as_view(), name="login"),
    path("logout/", UserLogoutView.as_view(), name="logout"),
    path("signup/tutor/", tutor_signup, name="tutor-signup"),
    path("signup/student/", student_signup, name="student-signup"),
    path("profile/", PersonDetailUpdateView.as_view(), name="profile"),
    path("profile/<int:pk>", PublicProfileView.as_view(), name="public-profile"),
    path("activate/<uidb64>/<token>", activate, name="activate"),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/models.py
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin
from django.db import models
from django.utils import timezone
from django.utils.translation import gettext_lazy
from users.managers import CustomUserManager


class CustomUser(AbstractBaseUser, PermissionsMixin):
    USERNAME_FIELD = "email"
    objects = CustomUserManager()

    email = models.EmailField(gettext_lazy("email adress"), unique=True)
    first_name = models.TextField()
    last_name = models.TextField()
    is_tutor = models.BooleanField(default=False)
    is_staff = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    date_joined = models.DateTimeField(default=timezone.now)
    google_credentials = models.JSONField(null=True, blank=True)
    google_email = models.EmailField(max_length=254, unique=True, null=True, blank=True)

    def __str__(self):
        return self.email

    def get_full_name(self):
        return f"{self.first_name} {self.last_name}"


class Profile(models.Model):
    user = models.OneToOneField(
        CustomUser, on_delete=models.CASCADE, related_name="profile"
    )
    profile_picture = models.ImageField(
        upload_to="profile_pics/",
        null=True,
        blank=True,
        default="profile_pics/user_pfp.png",
    )
    description = models.TextField(blank=True)

    @property
    def price_lists(self):
        return self.pricelist_set.all()

    def __str__(self):
        return self.user.email

users/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import AuthenticationForm
from users.models import CustomUser, Profile
from django import forms
from django.forms import ModelForm

User = get_user_model()


class ProfilePictureForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ["profile_picture"]


class CombinedForm(forms.ModelForm):
    description = forms.CharField()  # Add other fields from Profile as needed

    class Meta:
        model = CustomUser
        fields = ["email", "first_name", "last_name", "description"]

    def save(self, commit=True):
        user = super().save(commit=False)
        profile_description = self.cleaned_data.pop("description", None)

        if commit:
            user.save()
            user.profile.description = profile_description
            user.profile.save()

        return user


class UserForm(forms.ModelForm):
    class Meta:
        model = CustomUser
        fields = ["email", "first_name", "last_name"]


class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ["description"]


class CustomAuthenticationForm(AuthenticationForm):
    username = forms.EmailField(
        label="Email", widget=forms.EmailInput(attrs={"autofocus": True})
    )

    def clean_username(self):
        username = self.cleaned_data.get("username")
        return username.lower()


class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = CustomUser
        fields = ("email", "first_name", "last_name")


class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = CustomUser
        fields = ("email",)


# class StudentProfileForm(ModelForm):
#     class Meta:
#         model = StudentProfile
#         fields = ["description_student"]


class CustomUserForm(ModelForm):
    class Meta:
        model = CustomUser
        fields = ["first_name", "last_name"]

users/views.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import reverse_lazy
from users.forms import CustomUserCreationForm
from django.shortcuts import render, redirect
from django.views.generic.base import TemplateView
from users.models import CustomUser
from django.views.generic.detail import DetailView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages
from django.http import Http404
from django.shortcuts import get_object_or_404
from users.forms import UserForm, ProfileForm, ProfilePictureForm
from django.contrib.auth import get_user_model

# imports for mail
from users.tokens import account_activation_token
from django.contrib.sites.shortcuts import get_current_site
from django.template.loader import render_to_string
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.utils.encoding import force_bytes, force_str
from django.core.mail import EmailMessage


class PersonDetailUpdateView(LoginRequiredMixin, TemplateView):
    template_name = "users/profile.html"

    def get(self, request, *args, **kwargs):
        user_form = UserForm(instance=request.user)
        profile_form = ProfileForm(instance=request.user.profile)
        picture_form = ProfilePictureForm(instance=request.user.profile)
        return self.render_to_response(
            {
                "user_form": user_form,
                "profile_form": profile_form,
                "picture_form": picture_form,
            }
        )

    def post(self, request, *args, **kwargs):
        user_form = UserForm(request.POST, instance=request.user)
        profile_form = ProfileForm(
            request.POST, request.FILES, instance=request.user.profile
        )
        picture_form = ProfilePictureForm(
            request.POST, request.FILES, instance=request.user.profile
        )

        if "profile_picture" in request.FILES and picture_form.is_valid():
            picture_form.save()

        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()

        return redirect("profile")  # Replace 'profile' with your success URL


class PublicProfileView(LoginRequiredMixin, DetailView):
    model = CustomUser
    template_name = "users/public-profile.html"
    context_object_name = "current_profile_user"
    login_url = reverse_lazy("login")

    def get_object(self, queryset=None):
        user = get_object_or_404(CustomUser, pk=self.kwargs.get("pk"))

        # if user.is_tutor:
        return user
        # else:
        #     raise Http404("User is not a tutor.")


class UserLoginView(LoginView):
    template_name = "users/login.html"
    redirect_authenticated_user = True
    success_url = reverse_lazy("profile")

    def form_valid(self, form):
        messages.success(self.request, "You have successfully logged in.")
        return super().form_valid(form)

    def form_invalid(self, form):
        messages.error(
            self.request, "Login failed. Please try again.", extra_tags="danger"
        )
        return super().form_invalid(form)


class UserLogoutView(LogoutView):
    template_name = "users/logout.html"
    next_page = reverse_lazy("home")

    def dispatch(self, request, *args, **kwargs):
        messages.success(request, "You have successfully logged out.")
        return super().dispatch(request, *args, **kwargs)


def tutor_signup(request):
    if request.method == "POST":
        user_form = CustomUserCreationForm(request.POST)
        if user_form.is_valid():
            user = user_form.save(commit=False)
            user.is_tutor = True
            user.is_active = False
            user.save()
            activateEmail(request, user, user_form.cleaned_data.get("email"))
            return redirect("login")

    else:
        user_form = CustomUserCreationForm()
    return render(
        request,
        "users/tutor_signup.html",
        {"user_form": user_form},
    )


def student_signup(request):
    if request.method == "POST":
        user_form = CustomUserCreationForm(request.POST)
        if user_form.is_valid():
            user = user_form.save(commit=False)
            user.is_tutor = False
            user.is_active = False
            user.save()
            activateEmail(request, user, user_form.cleaned_data.get("email"))
            return redirect("login")
    else:
        user_form = CustomUserCreationForm()
    return render(
        request,
        "users/student_signup.html",
        {"user_form": user_form},
    )


def activate(request, uidb64, token):
    user_model = get_user_model()
    try:
        uid = force_str(urlsafe_base64_decode(uidb64))
        user = user_model.objects.get(pk=uid)
    except (TypeError, ValueError, OverflowError, user.DoesNotExist):  # srapwdzic
        user = None

    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.save()

        messages.success(request, "You've activated your account, log in now.")
        return redirect("login")
    else:
        messages.error(request, "Link is invalid!")

    return redirect("landing-page")


def activateEmail(request, user, to_email):
    mail_subject = "Activate link - tutorApp"
    message = render_to_string(
        "users/email.html",
        {
            "domain": get_current_site(request).domain,
            "uid": urlsafe_base64_encode(force_bytes(user.pk)),
            "token": account_activation_token.make_token(user),
            "protocol": "https" if request.is_secure() else "http",
        },
    )
    email = EmailMessage(mail_subject, message, to=[to_email])
    if email.send():
        messages.success(
            request, f"Activate your account at {to_email} please check spam folder"
        )
    else:
        messages.error(
            request,
            "Something went wrong... check if you have entered correct email",
        )

users/templates/users/email.html
{% autoescape off %}

Hi!

Click link below to verify your email.

http://{{ domain }}{% url 'activate' uidb64=uid token=token %}
{% endautoescape %}

users/templates/users/login.html
{% extends "app/base-index.html" %}
{% load static %}
{% block content %}
<body>
    <section class="position-relative py-4 py-xl-5" style="text-align: left;">
        <div id="signup-container" class="container">
            <div class="row mb-5">
                <div class="col-md-8 col-xl-6 text-center mx-auto">
                    <h2>Log in</h2>
                    <p class="w-lg-50"></p>
                </div>
            </div>
            <div class="row d-flex justify-content-center">
                <div class="col-md-6 col-xl-4">
                    <div class="card mb-5">
                        <div class="card-body d-flex flex-column align-items-center">
                            <div class="bs-icon-xl bs-icon-circle bs-icon-primary bs-icon my-4"><svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" fill="currentColor" viewBox="0 0 16 16" class="bi bi-person">
                                    <path d="M8 8a3 3 0 1 0 0-6 3 3 0 0 0 0 6Zm2-3a2 2 0 1 1-4 0 2 2 0 0 1 4 0Zm4 8c0 1-1 1-1 1H3s-1 0-1-1 1-4 6-4 6 3 6 4Zm-1-.004c-.001-.246-.154-.986-.832-1.664C11.516 10.68 10.289 10 8 10c-2.29 0-3.516.68-4.168 1.332-.678.678-.83 1.418-.832 1.664h10Z"></path>
                                </svg></div>
                            <form class="text-center" method="post">
                                {% csrf_token %}
                                <div class="mb-3"><input class="form-control" type="username" name="username" placeholder="Email"></div>
                                <div class="mb-3"><input class="form-control" type="password" name="password" placeholder="Password"></div>
                                <div class="mb-3"><button class="btn btn-primary d-block w-100" type="submit" value="submit">Login</button></div>
                                <p class="text-muted">Forgot your password?</p>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
  <main id="main" class="main">
    {% if messages %}
      {% for message in messages %}
        <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
          {{ message }}
        </div>
      {% endfor %}
    {% endif %}
  </main>
    <script src="{% static 'assets/bootstrap/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'assets/js/Responsive-Active-Navbar-script.js' %}"></script>
</body>
{% endblock %}

users/templates/users/logout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>logout</title>
</head>
<body>
<h1>Logout successful</h1>
</body>
</html>

users/templates/users/profile.html
{% extends "app/base-new-student.html" %}

{% block content %}
<div class="container-fluid">
    <h3 class="text-dark mb-4">Profile</h3>
    <div class="row mb-3">
        <div class="col-lg-4">
            <div class="card mb-3">
                <div class="card-body text-center shadow"><img class="rounded-circle mb-3 mt-4" src="{{ user.profile.profile_picture.url }}" width="160" height="160">
                    <div class="mb-3">
                        <form id="profile-picture-form" method="post" enctype="multipart/form-data" style="display: none;">
                            {% csrf_token %}
                            {{ picture_form.profile_picture }}
                        </form>
                        <button class="btn btn-primary btn-sm btn-change-photo" type="button">Change Photo</button>
                    </div>
                    <div class="mb-3">
                        <p style="color: black"> Wallet balance = {{ user.wallet.balance }}PLN</p>
                    </div>
                </div>
            </div>
            <div class="card shadow mb-4">
                <div class="card-header py-3">
                    <h6 class="text-primary fw-bold m-0">Upcoming lessons</h6>
                </div>
                <div class="card-body">
                    {% if not user.is_tutor %}
                        {% for lesson in  user.student_lessons.all %}
                            <h4 class="small fw-bold"><a href="{% url 'lesson-list' %}" style="color: black; text-decoration-style: solid;">{{ lesson.get_subject_display }} with tutor: {{ lesson.tutor.get_full_name }}</a><span class="float-end">{{ lesson.date }} | {{ lesson.start_time }}</span></h4>
        {#                    <div class="progress progress-sm mb-3">#}
        {#                        <div class="progress-bar bg-danger" aria-valuenow="20" aria-valuemin="0" aria-valuemax="100" style="width: 20%;"><span class="visually-hidden">20%</span></div>#}
        {#                    </div>#}
                            <br>
                        {% endfor %}
                    {% else %}
                        {% for lesson in  user.tutor_lessons.all %}
                        <h4 class="small fw-bold"><a href="{% url 'update-lesson' lesson.id %}">{{ lesson.get_subject_display }} with student: {{ lesson.student.get_full_name }}</a><span class="float-end">{{ lesson.date }} | {{ lesson.start_time }}</span></h4>
    {#                    <div class="progress progress-sm mb-3">#}
    {#                        <div class="progress-bar bg-danger" aria-valuenow="20" aria-valuemin="0" aria-valuemax="100" style="width: 20%;"><span class="visually-hidden">20%</span></div>#}
    {#                    </div>#}
                        <br>
                        {% endfor %}
                    {% endif %}
                    {% if user.google_credentials %}
                    <button class="btn btn-primary btn-sm btn-success" disabled type="button">Google calendar connected.</button>
                    {% else %}
                    <a href="{% url 'start-auth' %}"><button class="btn btn-primary btn-sm btn-danger" type="button">Google calendar sign in</button></a>
                    {% endif %}
                </div>
            </div>
        </div>
        <div class="col-lg-8">
            <div class="row mb-3 d-none">
                <div class="col">
                    <div class="card text-white bg-primary shadow">
                        <div class="card-body">
                            <div class="row mb-2">
                                <div class="col">
                                    <p class="m-0">Peformance</p>
                                    <p class="m-0"><strong>65.2%</strong></p>
                                </div>
                                <div class="col-auto"><i class="fas fa-rocket fa-2x"></i></div>
                            </div>
                            <p class="text-white-50 small m-0"><i class="fas fa-arrow-up"></i>&nbsp;5% since last month</p>
                        </div>
                    </div>
                </div>
                <div class="col">
                    <div class="card text-white bg-success shadow">
                        <div class="card-body">
                            <div class="row mb-2">
                                <div class="col">
                                    <p class="m-0">Peformance</p>
                                    <p class="m-0"><strong>65.2%</strong></p>
                                </div>
                                <div class="col-auto"><i class="fas fa-rocket fa-2x"></i></div>
                            </div>
                            <p class="text-white-50 small m-0"><i class="fas fa-arrow-up"></i>&nbsp;5% since last month</p>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col">
                    <div class="card shadow mb-3">
                        <div class="card-header py-3">
                            <p class="text-primary m-0 fw-bold">User Settings</p>
                        </div>
                        <div class="card-body">
                            <form method="post">
                                {% csrf_token %}
                                <div class="row">
                                    <div class="col">
                                        <div class="mb-3">
                                            <label class="form-label" for="id_description"><strong>Description</strong></label>
                                            <input class="form-control" type="text" id="id_description" placeholder="{{ user.profile.description }}" name="description" value="{{ profile_form.description.value }}">
                                        </div>
                                    </div>
                                    <div class="col">
                                        <div class="mb-3">
                                            <label class="form-label" for="id_email"><strong>Email Address</strong></label>
                                            <input class="form-control" type="email" id="id_email" name="email" value="{{ user_form.email.value }}">
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col">
                                        <div class="mb-3">
                                            <label class="form-label" for="id_first_name"><strong>First Name</strong></label>
                                            <input class="form-control" type="text" id="id_first_name" name="first_name" value="{{ user_form.first_name.value }}">
                                        </div>
                                    </div>
                                    <div class="col">
                                        <div class="mb-3">
                                            <label class="form-label" for="id_last_name"><strong>Last Name</strong></label>
                                            <input class="form-control" type="text" id="id_last_name" name="last_name" value="{{ user_form.last_name.value }}">
                                        </div>
                                    </div>
                                </div>
                                <div class="mb-3">
                                    <button class="btn btn-primary btn-sm" type="submit">Save Settings</button>
                                </div>
                            </form>
                        </div>
                    </div>
                    <div class="card shadow">
                        <div class="card-header py-3">
                            <p class="text-primary m-0 fw-bold">Contact Settings</p>
                        </div>
                        <div class="card-body">
                            <form>
                                <div class="mb-3"><label class="form-label" for="address"><strong>Address</strong></label><input class="form-control" type="text" id="address" placeholder="Sunset Blvd, 38" name="address"></div>
                                <div class="row">
                                    <div class="col">
                                        <div class="mb-3"><label class="form-label" for="city"><strong>City</strong></label><input class="form-control" type="text" id="city" placeholder="Los Angeles" name="city"></div>
                                    </div>
                                    <div class="col">
                                        <div class="mb-3"><label class="form-label" for="country"><strong>Country</strong></label><input class="form-control" type="text" id="country" placeholder="USA" name="country"></div>
                                    </div>
                                </div>
                                <div class="mb-3"><button class="btn btn-primary btn-sm" type="submit">Save&nbsp;Settings</button></div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="card shadow mb-5">
        <div class="card-header py-3">
            <p class="text-primary m-0 fw-bold">Reviews</p>
        </div>
        <div class="card-body">
            <div class="row">
                <div class="col-md-6">
                    <form>
                        <div class="mb-3"><label class="form-label" for="signature"><strong>Signature</strong><br></label><textarea class="form-control" id="signature" rows="4" name="signature"></textarea></div>
                        <div class="mb-3">
                            <div class="form-check form-switch"><input class="form-check-input" type="checkbox" id="formCheck-1"><label class="form-check-label" for="formCheck-1"><strong>Notify me about new replies</strong></label></div>
                        </div>
                        <div class="mb-3"><button class="btn btn-primary btn-sm" type="submit">Save Settings</button></div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

users/templates/users/student_signup.html
{% extends "app/base-index.html" %}
{% load static %}

{% block content %}
<body>
    <section id="signup-section" class="position-relative py-4 py-xl-5" style="text-align: left;">
        <div id="signup-container" class="container">
            <div class="row mb-5">
                <div class="col-md-8 col-xl-6 text-center mx-auto">
                    <h2>Student</h2>
                    <h2>Sign up</h2>
                    <p class="w-lg-50"></p>
                </div>
            </div>
            <div class="row d-flex justify-content-center">
                <div class="col-md-6 col-xl-4">
                    <div class="card mb-5">
                        <div class="card-body d-flex flex-column align-items-center">
                            <div class="bs-icon-xl bs-icon-circle bs-icon-primary bs-icon my-4"><svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" fill="currentColor" viewBox="0 0 16 16" class="bi bi-person">
                                    <path d="M8 8a3 3 0 1 0 0-6 3 3 0 0 0 0 6Zm2-3a2 2 0 1 1-4 0 2 2 0 0 1 4 0Zm4 8c0 1-1 1-1 1H3s-1 0-1-1 1-4 6-4 6 3 6 4Zm-1-.004c-.001-.246-.154-.986-.832-1.664C11.516 10.68 10.289 10 8 10c-2.29 0-3.516.68-4.168 1.332-.678.678-.83 1.418-.832 1.664h10Z"></path>
                                </svg></div>
                            <form class="text-center" method="post">
                                {% csrf_token %}
                                <div class="mb-3"><input class="form-control" type="email" name="email" placeholder="Email"></div>
                                <div class="mb-3"><input class="form-control" type="text" name="first_name" placeholder="First name"></div>
                                <div class="mb-3"><input class="form-control" type="text" name="last_name" placeholder="Last name"></div>
                                <div class="mb-3"><input class="form-control" type="password" name="password1" placeholder="Password"></div>
                                <div class="mb-3"><input class="form-control" type="password" name="password2" placeholder="repeat password"></div>
                                <div class="mb-3"><button class="btn btn-primary d-block w-100" type="submit">Register</button></div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
</body>
{% endblock %}

users/templates/users/tutor_signup.html
{% extends "app/base-index.html" %}
{% load static %}


{% block content %}
<body>
    <section class="position-relative py-4 py-xl-5" style="text-align: left;">
        <div id="signup-container" class="container">
            <div class="row mb-5">
                <div class="col-md-8 col-xl-6 text-center mx-auto">
                    <h2>Tutor</h2>
                    <h2>Sign up</h2>
                    <p class="w-lg-50"></p>
                </div>
            </div>
            <div class="row d-flex justify-content-center">
                <div class="col-md-6 col-xl-4">
                    <div class="card mb-5">
                        <div class="card-body d-flex flex-column align-items-center">
                            <div class="bs-icon-xl bs-icon-circle bs-icon-primary bs-icon my-4"><svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" fill="currentColor" viewBox="0 0 16 16" class="bi bi-person">
                                    <path d="M8 8a3 3 0 1 0 0-6 3 3 0 0 0 0 6Zm2-3a2 2 0 1 1-4 0 2 2 0 0 1 4 0Zm4 8c0 1-1 1-1 1H3s-1 0-1-1 1-4 6-4 6 3 6 4Zm-1-.004c-.001-.246-.154-.986-.832-1.664C11.516 10.68 10.289 10 8 10c-2.29 0-3.516.68-4.168 1.332-.678.678-.83 1.418-.832 1.664h10Z"></path>
                                </svg></div>
                            <form class="text-center" method="post">
                                {% csrf_token %}
                                <div class="mb-3"><input class="form-control" type="email" name="email" placeholder="Email"></div>
                                <div class="mb-3"><input class="form-control" type="text" name="first_name" placeholder="First name"></div>
                                <div class="mb-3"><input class="form-control" type="text" name="last_name" placeholder="Last name"></div>
                                <div class="mb-3"><input class="form-control" type="password" name="password1" placeholder="Password"></div>
                                <div class="mb-3"><input class="form-control" type="password" name="password2" placeholder="Repeat password"></div>
                                <div class="mb-3"><button class="btn btn-primary d-block w-100" type="submit">Login</button></div>
                                <p class="text-muted">Forgot your password?</p>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <main id="main" class="main">
        {% if messages %}
          {% for message in messages %}
            <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
              {{ message }}
            </div>
          {% endfor %}
        {% endif %}
    </main>
    <script src="{% static 'assets/bootstrap/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'assets/js/Responsive-Active-Navbar-script.js' %}"></script>
</body>
{% endblock %}